### ISSUE TITLE
Object Distance Estimation Base Code

### ISSUE THREAD

**Issue by hmd0404-nitk-eee** [Vidyut-Projects-2k22/Scene-Description#1]
### Tasks
- Derive the formula for calculating approximate distance from camera.
- Code it in python.
- Include change of units for the output distance. Input Parameters may be left with their default units.

### Actions later on
- Connecting this script with YOLO Object Detection.
- Faking Stereo setup by two laterally shifted image inputs.

**Comment by hmd0404-nitk-eee** [comment]
## TODOs:
- [ ] Push the basic code, with proper variable names and basic outlining comments. 
- [ ] Fix Object Depth Estimation errors, using different possible techniques.
- [ ] Push the updated code with ODE and its comments.
